name: Release esusab-java
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The library version. For consistency, it should be the the LEDI APS Version on https://integracao.esusab.ufsc.br/ledi/index.html'
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move java classes
        run: |
          mv thrift/layout-ras/gen-javabean/br library/esusab-java/src/main/java